<a href="https://colab.research.google.com/github/anjitha2002/Crab-Age-Prediction-Using-Machine-Learning-Regression/blob/main/Crab_Age_Prediction_Using_Machine_Learning_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [39]:
train_data=pd.read_csv("/content/train.csv")
test_data=pd.read_csv("/content/test.csv")

In [40]:
train_data

,id,Sex,Length,Diameter,Height,Weight,Shucked Weight,Viscera Weight,Shell Weight,Age
0,0,I,0.9125,0.6875,0.2250,6.336113,2.721552,1.842718,2.267960,6.0
1,1,F,1.4875,1.1500,0.3750,30.107169,13.139993,9.539607,7.654365,9.0
2,2,F,1.5625,1.2125,0.4250,33.381536,16.683681,7.144074,9.596306,9.0
3,3,F,1.4875,1.2000,0.3750,35.011632,17.080574,7.767763,8.802520,12.0
4,4,M,1.6250,1.3000,0.3750,41.560367,19.036689,8.816695,11.339800,11.0
...,...,...,...,...,...,...,...,...,...,...
14995,14995,M,0.7250,0.5250,0.1875,3.274367,1.219029,0.807961,1.133980,7.0
14996,14996,M,1.0875,0.8375,0.2750,9.199413,4.323299,1.786018,3.685435,9.0
14997,14997,F,1.2000,0.9500,0.3375,15.378051,7.555142,2.721552,4.167376,10.0
14998,14998,I,1.0750,0.8125,0.2875,10.418441,4.734367,2.636503,3.401940,7.0
14999,14999,F,1.4375,1.1000,0.4125,25.883094,10.914558,6.251065,7.087375,10.0

In [41]:
test_data

,id,Sex,Length,Diameter,Height,Weight,Shucked Weight,Viscera Weight,Shell Weight
0,15000,I,1.1625,0.8750,0.2750,11.708343,4.918638,2.409708,3.685435
1,15001,M,1.4125,1.1375,0.3875,23.430862,9.879801,5.400580,7.087375
2,15002,I,0.7250,0.5250,0.1500,2.438057,1.190679,0.623689,0.850485
3,15003,M,1.4875,1.1875,0.4500,31.326197,12.587178,7.044851,8.646598
4,15004,M,1.5750,1.2000,0.4375,36.073741,17.491642,7.342521,9.199413
...,...,...,...,...,...,...,...,...,...
9995,24995,M,1.4750,1.1750,0.3625,28.066005,10.645237,6.137667,8.363103
9996,24996,M,1.6500,1.3250,0.4875,45.231627,14.968536,9.893975,15.025235
9997,24997,I,1.1125,0.8750,0.3500,13.040770,5.953395,3.189319,3.827183
9998,24998,F,0.5625,0.3750,0.1250,1.488349,0.467767,0.425243,0.425243
9999,24999,M,1.5625,1.2000,0.4000,33.466585,18.909116,7.399220,8.930093

In [42]:
train_data.isnull().sum()

id                0
Sex               0
Length            0
Diameter          0
Height            0
Weight            0
Shucked Weight    0
Viscera Weight    0
Shell Weight      0
Age               0
dtype: int64

In [43]:
test_data.isnull().sum()

id                0
Sex               0
Length            0
Diameter          0
Height            0
Weight            0
Shucked Weight    0
Viscera Weight    0
Shell Weight      0
dtype: int64

In [44]:
train_data['Sex'].value_counts()

Sex
M    5565
I    4979
F    4456
Name: count, dtype: int64

In [45]:
test_data['Sex'].value_counts()

Sex
M    3651
I    3343
F    3006
Name: count, dtype: int64

In [46]:
le=LabelEncoder()

In [47]:
train_data['Sex']=le.fit_transform(train_data['Sex'])

In [48]:
test_data['Sex']=le.fit_transform(test_data['Sex'])

In [49]:
train_data=train_data.drop(columns=["id"])
test_data=test_data.drop(columns=['id'])

In [50]:
train_data

,Sex,Length,Diameter,Height,Weight,Shucked Weight,Viscera Weight,Shell Weight,Age
0,1,0.9125,0.6875,0.2250,6.336113,2.721552,1.842718,2.267960,6.0
1,0,1.4875,1.1500,0.3750,30.107169,13.139993,9.539607,7.654365,9.0
2,0,1.5625,1.2125,0.4250,33.381536,16.683681,7.144074,9.596306,9.0
3,0,1.4875,1.2000,0.3750,35.011632,17.080574,7.767763,8.802520,12.0
4,2,1.6250,1.3000,0.3750,41.560367,19.036689,8.816695,11.339800,11.0
...,...,...,...,...,...,...,...,...,...
14995,2,0.7250,0.5250,0.1875,3.274367,1.219029,0.807961,1.133980,7.0
14996,2,1.0875,0.8375,0.2750,9.199413,4.323299,1.786018,3.685435,9.0
14997,0,1.2000,0.9500,0.3375,15.378051,7.555142,2.721552,4.167376,10.0
14998,1,1.0750,0.8125,0.2875,10.418441,4.734367,2.636503,3.401940,7.0
14999,0,1.4375,1.1000,0.4125,25.883094,10.914558,6.251065,7.087375,10.0

In [51]:
X=train_data.drop(columns=['Age'],axis=1)
y=train_data['Age']

In [52]:
scaler=StandardScaler()

In [53]:
X_scaled=scaler.fit_transform(X)

In [54]:
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,random_state=42)

In [55]:
print(X_train)

[[-1.31932391  0.90577184  0.8564402  ...  0.37117168  0.27310452
   0.80460443]
 [-1.31932391  1.03563905  1.01401129 ...  0.88570611  0.62399992
   0.96900008]
 [-0.09082688 -0.30632212 -0.40412853 ... -0.78525717 -0.89146139
  -0.74312049]
 ...
 [-1.31932391  1.16550626  1.11905869 ...  1.02834932  1.62583173
   1.53035109]
 [ 1.13767015  0.73261556  0.69886911 ...  0.96466931  1.11728766
   0.46378418]
 [ 1.13767015  0.73261556  0.8564402  ...  0.34060528  0.48669302
   0.39562012]]

In [56]:
models={
    'Linear Regression':LinearRegression(),
    'Random Forest':RandomForestRegressor(n_estimators=100,random_state=42),
    'Gradient Booster':GradientBoostingRegressor(random_state=42),
    'Decision Tree':DecisionTreeRegressor(random_state=42),

}

In [57]:
result=[]
for name,model in models.items():
  model.fit(X_train,y_train)
  y_pred=model.predict(X_test)

  mae=mean_absolute_error(y_test,y_pred)
  mse=mean_squared_error(y_test,y_pred)
  r2=r2_score(y_test,y_pred)

  result.append({
      "Model":name,
      "MAE":mae,
      "MSE":mse,
      "R2 Score":r2
  })

In [58]:
result_df=pd.DataFrame(result)

In [59]:
result_df

               Model       MAE       MSE  R2 Score
0  Linear Regression  1.488642  4.532008  0.564992
1      Random Forest  1.442943  4.329956  0.584386
2   Gradient Booster  1.415712  4.236709  0.593337
3      Decision Tree  1.979500  8.954083  0.140537

In [60]:
best_model=result_df.sort_values(by="MAE")
best_model

               Model       MAE       MSE  R2 Score
2   Gradient Booster  1.415712  4.236709  0.593337
1      Random Forest  1.442943  4.329956  0.584386
0  Linear Regression  1.488642  4.532008  0.564992
3      Decision Tree  1.979500  8.954083  0.140537

In [61]:
best_model=GradientBoostingRegressor(random_state=42)
best_model.fit(X,y)

GradientBoostingRegressor(random_state=42)

In [62]:
test_pred=best_model.predict(test_data)

In [63]:
sub=pd.read_csv("/content/sample_submission.csv")

In [64]:
sub

         id  Age
0     15000   10
1     15001   10
2     15002   10
3     15003   10
4     15004   10
...     ...  ...
9995  24995   10
9996  24996   10
9997  24997   10
9998  24998   10
9999  24999   10

[10000 rows x 2 columns]

In [65]:
sub['Age']=test_pred

In [66]:
sub

         id        Age
0     15000   7.973773
1     15001  10.715109
2     15002   5.380970
3     15003  11.428295
4     15004  10.460844
...     ...        ...
9995  24995  12.278193
9996  24996  17.461398
9997  24997   8.797080
9998  24998   7.936635
9999  24999   9.834020

[10000 rows x 2 columns]

In [67]:
print(sub.columns)

Index(['id', 'Age'], dtype='object')

In [68]:
sub.to_csv("submission.csv",index=False)

In [69]:
from google.colab import files
files.download("submission.csv")